[VALD_CONFIG]
client_id = "nx46BPhS92F0rl8w=="
client_secret = "7daFiGniBsGY7QGSKS41cbSuNlr0bZpfQ="
tenant_id = "28887524-c9e0-4783-84a8-5d6ecc41c239"
token_url = "https://security.valdperformance.com/connect/token"
forcedecks_base_url = "https://prd-use-api-extforcedecks.valdperformance.com"
profiles_base_url = "https://prd-use-api-extprofiles.valdperformance.com/externalprofiles/v2024q2"